---
- name: Start splunk container
  docker_container:
    name: "{{ splunk_container_name }}"
    image: "{{ splunk_image_name }}"
    state: started
    recreate: yes
    user: root
    hostname: "{{ splunk_hostname }}"
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ splunk_external_port}}:{{ splunk_internal_port }}"
     - "{{ splunk_rest_port }}:{{ splunk_rest_port }}"
    volumes:
     - "{{ splunk_audit_volume }}:{{ splunk_audit_directory }}"
    env:
<<<<<<< HEAD
      SPLUNK_START_ARGS="--accept-license --seed-passwd "{{ splunk_account_password }}""
      SPLUNK_USER="root"
=======
      SPLUNK_START_ARGS="--accept-license"
      SPLUNK_PASSWORD="{{ splunk_account_password }}"
      DEBUG="true"
      SPLUNK_HOME_OWNERSHIP_ENFORCEMENT="false"
      SPLUNK_ADD="monitor /conjur/audit.json"
>>>>>>> fix-stuff
    restart_policy: always

- name: Wait for Splunk to start
  uri:
    url: "http://localhost:8000/en-US/account/login?return_to=%2Fen-US%2F"
    return_content: yes
  register: webpage
  until: '"Splunk Inc" in webpage.content'
  retries: 36
  delay: 5

- name: Add monitor for Conjur audit file
  shell: |
    sudo docker exec splunk \
    bin/splunk add monitor /conjur/audit.json -auth admin:{{ splunk_account_password }}

- name: Change permissions on audit.json
  shell: |
    docker exec {{ conjur_container_name }} chmod 777 {{ conjur_audit_directory }}/audit.json

- name: Add splunk monitor
  shell: |
    docker exec {{ splunk_container_name }} /opt/splunk/bin/splunk add monitor /conjur/audit.json -auth {{ splunk_account }}:{{ splunk_account_password }}

- name: Create Conjur Dashboard
  uri:
    url: "https://localhost:{{ splunk_rest_port }}/servicesNS/admin/search/data/ui/views"
    user: admin
    password: "{{ splunk_account_password }}"
    status_code: 201
    method: POST
    body: "name=conjur&eai:data={{ lookup('file','files/conjur_dashboard.xml') }}"
    validate_certs: no
