---
# handlers file for machinePrep
- name: restartDocker
  service:
    name: docker
    state: started
  listen: "start docker"

- name: enableDocker
  service:
    name: docker
    enabled: yes
  listen: "start docker"