- !policy
  id: frontend
  body:
    - &variables 
      - !variable helloworld_secret
      - !variable database_password
      - !variable web_config_password
      - !variable systema_root_sshkey
      - !variable systemb_root_sshkey
      - !variable aws_access_key
      - !variable aws_secret_key
    
    - &secrets
      - !variable sql_password

- !policy
  id: backend
  body:
    - &gogs 
      - !variable gogs_secure_user
      - !variable gogs_secure_user_password

    - &ansible
      - !variable ansible_secure_user
      - !variable ansible_secure_user_password

- !permit
  role: !group /devops
  privileges:
   - read
   - execute
  resource: *variables

- !permit
  role: !group /devops
  privileges:
   - read
   - execute
  resource: *gogs

- !permit
  role: !group /devops
  privileges:
   - read
   - execute
  resource: *ansible

- !permit
  role: !group /admins
  privileges:
   - read
   - execute
   - update
  resource: *variables

- !permit
  role: !group /admins
  privileges:
   - read
   - execute
   - update
  resource: *gogs

- !permit
  role: !group /admins
  privileges:
   - read
   - execute
   - update
  resource: *ansible

- !permit
  role: !group /auditors
  privileges:
   - read
  resource: *variables

- !permit
  role: !layer /jenkins/nodes
  privileges:
   - execute
  resource: *variables

- !permit
  role: !layer /jenkins/nodes
  privileges:
   - execute
  resource: *gogs

- !permit
  role: !layer /jenkins/nodes
  privileges:
   - execute
  resource: *ansible

- !permit
  role: !layer /tomcat/nodes
  privileges:
   - read
   - execute
  resource: *variables

- !permit
  role: !layer /webapp/nodes
  privileges:
   - read
   - execute
  resource: *variables