---
- name: Start postgres
  docker_container:
    name: database
    image: postgres:9.3
    state: started
    recreate: yes
    networks:
     - name: "{{ conjur_network_name }}"
    restart_policy: always

- name: Build nginx proxy
  docker_image:
    name: "{{ conjur_nginx_image_name }}"
    path: "{{ role_path }}/files/nginx_conf/"
    state: present
    force: yes

- name: Generate conjur data key
  shell: |
    docker container run --rm {{ conjur_OSS_image_name }} data-key generate
  register: conjur_data_key
  
- name: Start Conjur
  docker_container:
    name: "{{ conjur_OSS_container_name }}"
    image: "{{ conjur_OSS_image_name }}"
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ conjur_OSS_port }}:80"
    state: started
    recreate: yes
    env:
       DATABASE_URL: postgres://postgres@database/postgres
       CONJUR_DATA_KEY: "{{ conjur_data_key.stdout }}"
    restart_policy: always
    command: server

- name: Wait for conjur to start
  uri:
    url: "{{ conjur_OSS_url }}"
    return_content: yes
  register: webpage
  until: '"Your Conjur server is running!" in webpage.content'
  retries: 60
  delay: 3

- name: Start nginx proxy
  docker_container:
    name: "{{ conjur_container_name }}"
    image: "{{ conjur_nginx_image_name }}"
    networks:
     - name: "{{ conjur_network_name }}"
    state: started
    published_ports:
     - 8443:443
    recreate: yes
    restart_policy: always

- name: Configure account
  shell: |
    docker exec {{ conjur_OSS_container_name }} conjurctl account create {{ conjur_account }}
  register: account

- name: obtain api key
  shell: |
    docker exec {{ conjur_cli_container_name }} echo "{{ account.stdout }}" | awk '/admin:/{print $5}' | tr -d '\r\n'
  register: api_key

- name: configure cli for OSS
  shell: |
    docker exec {{ conjur_cli_container_name }} bash -c "conjur init -u https://{{ conjur_container_name }} -a {{ conjur_account }} <<< yes"
    docker exec {{ conjur_cli_container_name }} conjur authn login -u admin -p {{ api_key.stdout }}

- include_tasks: conjurFramework.yml